### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by jgwerner** [3Blades/onpremise#62]
Running Install.sh returns the following error after accepting the license agreement, regardless of whether `virtualen` has been activated or not:

Gregs-MBP:onpremise gregwerner$ ./install.sh
BSD 3-Clause License
...
...
Accept License (y/n)? [ENTER]: y
....Starting Install
-- Checking for virtualenv
./install.sh: line 85: unexpected EOF while looking for matching `"'
./install.sh: line 86: syntax error: unexpected end of file

**Comment by roachmd** [comment]
UPDATED
